### ISSUE TITLE
Example names in ansible playbook not in English

### ISSUE THREAD

**Issue by iburadempa** [ElektraInitiative/opensesame#1]
For non-German speakers a translation of the names in example playbook would be welcome.

**Comment by markus2330** [comment]
Thank you very much for reporting this problem! I agree!

**Comment by markus2330** [comment]
@atmaxinger can you do this when you update the playbook to work with the latest version of ansible-libelektra?

**Comment by markus2330** [comment]
@iburadempa should be fixed now, can you check if the examples are understandable for you?

Btw. https://github.com/ElektraInitiative/olimex-base/ might be also interesting for you.
