### ISSUE TITLE
update the architecture picture

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#101]
_Originally posted by @markus2330 in https://github.com/ElektraInitiative/opensesame/issues/93#issuecomment-1752837813_

**Comment by markus2330** [comment]
Who created the original picture?

**Comment by fel115** [comment]
@horenso and I created it. @horenso did you save the `.drawio` file?

**Comment by fel115** [comment]
I updated the information_flow image in PR #115

**Comment by markus2330** [comment]
I don't see it included in the mdbook documentation? Please add it there.

#115 didn't really use the documentation convention one sentence per line, please have a quick look over the mdbook documentation if everything is nice.
