### ISSUE TITLE
Sensors implement Alarm to set global state in Elektra

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#103]
https://github.com/ElektraInitiative/opensesame/blob/4c7aed4014e5d1e578e8e03371dde53205ef6d01/src/sensors.rs#L276-L282

In the Alarm path of the Sensors, the global Elektra state should be set and then the system signal `USER2` triggers the Alarm Clock.

**Comment by markus2330** [comment]
Why not simply do as it was before with the `kdb set`?

**Comment by fel115** [comment]
It was commented out before. 
https://github.com/ElektraInitiative/opensesame/blob/32e44e7246be86a5191b0107fd6486fee373d3f5/src/main.rs#L305-L310

**Comment by markus2330** [comment]
ok, let us do  #117 instead
