### ISSUE TITLE
error message wrong?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#105]
Given the configuration:

```
Enabled Modules: 
Buttons: true
, Garage: false
, Sensors: false
, ModIR: false
, Environment: true
, Weatherstation: false
, Battery: true
, Watchdog: false
```

I get the error:

```
Error reading buttons of board ENXIO: No such device or address
```

it might be the error from pre0.8 that read like:

```
Fehler beim Lesen der Knöpfe am Board 21....
```

The message read likes as if the board is called ENXIO?
Also translation seems to be missing.

@fel115 did you also see this error already?

**Comment by fel115** [comment]
I haven't seen this error so far. With the Buttons, I haven't had problems.
I think there is something broken with the `smbus` connection.
