### ISSUE TITLE
low battery seems to cause lights to turn on

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#110]
```
💡 Pressed switch outside or light button. Light switched on..
18:52
Haustür
💡 Pressed switch inside. Light switched on..
19:45
🕶️ Light was turned off.
19:48
```

```
🪫 Battery Capacity is below 50% at 42%
19:45
```

At 19:45 no button was pressed.

**Comment by fel115** [comment]
Could it be, that the pull-ups don't work at a low capacity?  According to the source code, I can't see a correlation between those events.

**Comment by markus2330** [comment]
Yes, I was also astonished. So you mean to use lower values for the pull-ups?

**Comment by fel115** [comment]
Yes, I thought, that the 3V Battery doesn't supply the board with 5V, so there could be a problem with the pull-ups which are using the 5V pins. But the Buttons have an external Power supply, so I don't think that the 5V is the reason.
