### ISSUE TITLE
complete/fix spec/ansible

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#12]
- [ ] add sensors
- [ ] improve descriptions etc.
- [ ] add tomltypes: simpletable, tablearray etc. to have a more beautiful (and non-broken) TOML files
- [ ] update to latest ansible-libelektra

**Comment by atmaxinger** [comment]
Regarding the TOML types, I can't get it to work with the specification.

We can add the meta key `tomltype` with value `tablearray` to `/sensors`, HOWEVER due to the nature of the `spec` plugin, these meta values will be removed BEFORE the TOML storage plugin is executed ...

**Comment by markus2330** [comment]
Yes, the spec plugin removes the metadata before it gets passed to the storage plugin. So the metadata needs to be set by Ansible.

I fixed the title.
