### ISSUE TITLE
TASTER_INNEN might lead to "Pressed 11" error

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#16]
Probably due to "too fast release speed" of a switch, TASTER_INNEN might lead to "Pressed 11" errors.

```
src/main.rs:479: 🔘 Pressed 11 (bin: 1011)
```

Could be either a software bug (that handle src/buttons.rs 271 does not cope with a too fast state change) or a wrong handling of debouncing.

**Comment by markus2330** [comment]
This problem is probably now much more apparent due to lower i2c speed introduced in 7018655756d7f1f1fedcff3ae2e3fcf581360f38

(But I don't think it was introduced by it.)

**Comment by fel115** [comment]
How does `epins2.unwrap()` behave when a button is pressed? Does it return zero or one for the pressed button? Additionally, what is the purpose of `PINS2_INIT`? Does it activate the `LED_LIGHT` and `LED_BELL`?

Regarding `line 312` of the button.rs file, the comment states that pressed buttons are considered logical 0. Could you clarify whether this refers to the set pins or the return value? Why is it necessary for `pins2` to be smaller than the old `pins2` when the pressed button is zero?

**Comment by fel115** [comment]
Ok so, the first 4 bits of the 8 bits of `pins2` indicate which button is pressed, and for a pressed button a bit is set to `0`. 
I understand it now. Thank you!

**Comment by markus2330** [comment]
This is a duplicate of #41
