### ISSUE TITLE
create .deb from CI

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#19]
TODO: description how @atmaxinger did it

**Comment by atmaxinger** [comment]
TBF, I think for the CI build we need to do a cross-compilation, not build in an emulated environment. As I remember, building all the Rust dependencies for opensesame took about 3 hours.

I'm trying to set up a CI build with cross-compilation.

**Comment by markus2330** [comment]
@atmaxinger if you didn't already do it before, consider it as nice-to-have. More important is having all the Ansible scripts in a nice form, as this cannot be done by anyone else so easily.

**Comment by atmaxinger** [comment]
I can do both, however for CI, someone else, probably you, needs to create a very simple working "Hello World" CI pipeline first, as I probably do not have the permissions in either Jenkins or Cirrus CI to create a new pipeline for this project.

**Comment by markus2330** [comment]
The permissions on Jenkins is not a problem, @lukashartl can give you access. But as @fel115 knows Jenkins very well and doesn't know Ansible at all it is quite obvious that all Ansible tasks you do are overall much more important. So please do everything related to Ansible/Olimex first.

**Comment by lukashartl** [comment]
I've created a new Role called `libelektra_releaser` which does not grant `admin` privileges, but allows to call build `libelektra.*` (incl. the release pipeline) and I've assigned this role to your user, @atmaxinger .
You'll receive an email with the credentials :rocket:
