### ISSUE TITLE
Adi collaborator

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/opensesame#26]
I need to somehow be added as collaborator to use the pipeline.
![image](https://github.com/ElektraInitiative/opensesame/assets/53004139/1e13d528-d474-4f7d-b101-3d6d8e15e8d5)

Maybe we can do it with curl, gh cli, or I can open a PR for something small.

**Comment by markus2330** [comment]
I invited you with "Triage" permissions, please check if it works.

**Comment by markus2330** [comment]
Btw. are you sure your account should be used? We have elektrabot for something like this.

**Comment by 4ydan** [comment]
Yea, it works now, thx.
