### ISSUE TITLE
cli options for running opensesame

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#28]
Add command-line options to the OpenSesame project to allow disabling specific sections of the main program, such as the `panic::set_hook function`, which currently lacks informative panic details. 

This idea of cli options was mentioned in this issue #6.

**Comment by markus2330** [comment]
Better we talk about this. In any case it is not urgent, you can simply use normal Elektra config and `kdb set ...` to change config.

**Comment by fel115** [comment]
Yes, I created this issue because I closed issue #6, so this information doesn't get lost.
