### ISSUE TITLE
CI: cargo test

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/opensesame#30]
I have quite some errors and warnings, maybe I missed installing something?

## Reproduce
Download this [Dockerfile](https://github.com/ElektraInitiative/opensesame/blob/4edc1a4fc38cfc20251432e7df1fd5014e6430f1/scripts/jenkins/Dockerfile)
```
 curl https://raw.githubusercontent.com/ElektraInitiative/opensesame/4edc1a4fc38cfc20251432e7df1fd5014e6430f1/scripts/jenkins/Dockerfile -o Dockerfile
```

Build and run it
```sh
docker build -t temp_sesam . --build-arg VARIANT=bullseye && docker run -it --rm temp_sesam
```` 

Install git and clone the repo 
```sh
apt-get update && apt-get install -y git && git clone https://github.com/ElektraInitiative/opensesame/ && cd opensesame
```

cargo test
```
cargo test
```

## Result
![image](https://github.com/ElektraInitiative/opensesame/assets/53004139/da685b2c-62e9-4adc-b015-8449e36d27dc)

**Comment by markus2330** [comment]
> cargo test

Can you please copy&paste, the important parts of the error message seem to missing. This is probably a permission error? Maybe the config is unnecessarily written in the test cases.

> cargo clippy

This should be easy to fix, simply use `write_all` instead.

> cargo fmt --check

Can be simply applied.

**Comment by fel115** [comment]
I tested your Dockerfile, but I wasn't able to install `libelektra`. Does `cargo build` work for you?

**Comment by markus2330** [comment]
@4ydan can you update the top post about what is already fixed? Is this now only about failing tests?

**Comment by 4ydan** [comment]
Updated the post, it is about the tests and the one clippy error.

**Comment by 4ydan** [comment]
> I tested your Dockerfile, but I wasn't able to install libelektra.
my dockerfile installs libelektra like this
```
```
is that fine?

> Does cargo build work for you?

let me rebuild the container quick

**Comment by 4ydan** [comment]
> Does cargo build work for you?

Yes works for me
![image](https://github.com/ElektraInitiative/opensesame/assets/53004139/521f04d0-2cd9-43a0-95e3-5120a9f28aba)

I updated the top post to perfectly reproduce my problem.

**Comment by 4ydan** [comment]
I think its just a bad elektra installation probably, I will try with the new cross image.

**Comment by fel115** [comment]
Now that I've finally reproduced the error, turns out it's because the default configuration with elektra wasn't set. You can fix this by using the `debian/postinst` script to set the default configuration before running the tests. Once you've done that, the error should be history!

By setting the default configuration, you'll make sure everything is set up properly and avoid those pesky issues during testing.

If you need more help or run into anything else, just give me a shout. 

![image](https://github.com/ElektraInitiative/opensesame/assets/133339595/74641145-9c0c-48d0-9e13-ae1b65b8f3cf)

**Comment by 4ydan** [comment]
Thank you cery much, I will try it out later

**Comment by 4ydan** [comment]
Works, we can add this to CI now too.

**Comment by markus2330** [comment]
Great, nice collaboration! :heart:
