### ISSUE TITLE
Clippy error

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/opensesame#34]
Same environment as in #30 

```
root@9d2cb8837ca1:/opensesame# cargo clippy
```

58 warnings and one error

![image](https://github.com/ElektraInitiative/opensesame/assets/53004139/f57d6dc5-d8bc-482e-ac1c-a3029a56b8bd)

Sorry I really dont want to disturb you with stuff that works on your machine, but we should probably at least fix the error and integrat this into CI for better quality.

**Comment by markus2330** [comment]
Yes, I agree, error must be fixed soon, warnings also in the mid-term.
