### ISSUE TITLE
No metadata "mountpoint"

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/opensesame#42]
![image](https://github.com/ElektraInitiative/opensesame/assets/53004139/9a36d201-470e-4fea-a8d3-59adc3ce98c8)
It's me again with another error. Not sure if I did something or something happened, so I will ask quick. It's the same setup as in #30, now I get this error when I want to run `postinst`.

**Comment by markus2330** [comment]
Thx for asking. Most probably it somehow didn't mount the right file. What does `kdb mount` or `kdb file spec:/sw/libelektra/opensesame/#0/current` say?

**Comment by fel115** [comment]
I think I had the same problem. And for solving the problem I executed `debian/postrm` and then again `debian/postinst`.

**Comment by 4ydan** [comment]
> What does `kdb mount` 
```
[2023-07-24T19:37:11.798Z] + kdb mount
```
> or `kdb file spec:/sw/libelektra/opensesame/#0/current` say?
```
[2023-07-24T19:37:12.459Z] + kdb file spec:/sw/libelektra/opensesame/#0/current
[2023-07-24T19:37:12.459Z] /usr/share/elektra/specification/default.ecf
```

from [this](https://build.libelektra.org/blue/organizations/jenkins/opensesame/detail/PR-38/38/pipeline) pipeline inside stage `Test`

**Comment by fel115** [comment]
I have no clue about the cause of this failure. However, based on the pipeline, we should modify the exit codes of the scripts to determine whether the job was successfully mounted or not.

**Comment by markus2330** [comment]
> /usr/share/elektra/specification/default.ecf

`spec:/sw/libelektra/opensesame/#0/current` was not mounted at all

I'll have a closer look after the PermaplanT release.

**Comment by markus2330** [comment]
> we should modify the exit codes of the scripts to determine whether the job was successfully mounted or not.

And also add a diagnostic `kdb mount` at the end.

**Comment by markus2330** [comment]
"No metadata mountpoint" basically means that the whole spec file was not mounted correctly at its place.
(It is easy to see that files/opensesame.spec has a mountpoint at the very top, line 15).

I can reproduce, if I simply execute `./debian/postinst` in the `opensesame` folder I also get the same error. But if I enter the `debian` folder and execute `./postinst` it works for me. Maybe this is the problem?

Imho the correct way is anyway to install the package. Executing `./postinst` by hand is imho only a workaround for development.

**Comment by fel115** [comment]
Maybe we could change the `postinst` script to be able to execute from any directory.

**Comment by markus2330** [comment]
I don't think it is needed, as it is only a dev tool. Simply documenting how to use it in #10 imho should be enough.
