### ISSUE TITLE
clang-sys conflict with elektra & libmodbus 

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#45]
PR #43 contains the information about this issue.

**Comment by fel115** [comment]
Should be removed with the last Commit in PR #43

**Comment by markus2330** [comment]
Great, so we can close this?

**Comment by fel115** [comment]
I see it is only closed with the latest commits, which aren't active in #43. I changed the `Cargo.toml` file to `
libmodbus = {git = "https://github.com/ElektraInitiative/libmodbus-rs.git", branch="test_lower_bindgen_version"}` and downgraded the bingen in `libmodbus-sys` which isn't best practices.

**Comment by markus2330** [comment]
Ok, let us wait until it is fixed in master.

**Comment by markus2330** [comment]
I created https://github.com/ElektraInitiative/opensesame/issues/67 for the upgrade. Can we now fix this or do we have now another incompatibility?

**Comment by fel115** [comment]
Now everything is working, I compiled it on my working desktop and on the olimex-board and it is working. I pushed the changes to PR #49.
