### ISSUE TITLE
create circuit diagram

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#47]
Having a circuit diagram would make setting up the whole Opensesame system way easier. With a picture showing all the connections, you can put together the hardware setup much faster. The circuit diagram gives you a visual guide to understand how everything is connected, making the assembly process quicker and simpler. It's like a handy reference to ensure you're hooking up the hardware correctly, so you can avoid mistakes and get Opensesame up and running without a hitch.

**Comment by fel115** [comment]
@markus2330, perhaps you could provide me with some pictures of the A20-Lime2 board and the MOD-IO2. With that, I can create the diagram.

**Comment by markus2330** [comment]
This is a great idea and I would like to have it. Unfortunately, it is out of scope for the current work, we are already quite behind the schedule to implement everything in TODO. This is, however, definitely within scope for Netidee!
