### ISSUE TITLE
Dump all Register weather station

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#48]
@markus2330 how important is this feature? Should it be implemented now?

**Comment by markus2330** [comment]
Not important, should be after main functionality of weather station (regular reporting weather data and weather warnings)

**Comment by fel115** [comment]
Ok, weather warnings are implemented (#43 ), what is meant by regular reporting weather data?

**Comment by markus2330** [comment]
Let us finish #43 first (info+warning). Next step is publishing on https://www.opensensemap.org/ (in a next PR but you can already base of #43)

**Comment by fel115** [comment]
PR to this issue #52
