### ISSUE TITLE
opensesame.spec - configure Nextcloud

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#5]
How to setup the Nextcloud configuration in opensesame.spec.

- [x] - url
- [x] - chat; chat/licht; chat/ping
- [x] - user
- [x] - password

If these keys are not configured, this panic occurs:
`thread 'main' panicked at 'Did not find the key '/sw/libelektra/opensesame/#0/current/nextcloud/url'!', src/config.rs:121:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: opensesame::config::Config::get
             at ./src/config.rs:121:4
   3: opensesame::nextcloud::Nextcloud::new
             at ./src/nextcloud.rs:20:9
   4: opensesame::main
             at ./src/main.rs:187:26
   5: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by markus2330** [comment]
Thanks for reporting this issue! I agree this should be documented.

To get the "chat", you need to look at the URL when you are connected in the chat in the Nextcloud interface:

`https://nextcloud.markus-raab.org/nextcloud/index.php/call/<THIS IS THE TOKEN>`

**Comment by markus2330** [comment]
You need the token (from the Nextcloud website) to write it in your configuration.

So first you visit https://nextcloud.markus-raab.org/nextcloud, do a login, navigate to the chat and copy the token from there to opensesame's config.

Please also document this.

**Comment by fel115** [comment]
It looks like the URL doesn't exists:
`Couldn't ping 👋 Opensesame 0.7.6 init 2023-05-26T08:55:37.925376849+02:00 because https://nextcloud.markus-raab.org/ocs/v2.php/apps/spreed/api/v1/chat/vkgub94i: Client Error: 404 Not Found`

I created in Nextcloud a new conversation and then I copied the token, but for some reason the chat can't be found.

**Comment by markus2330** [comment]
There is a misconfiguration in the base URL it should be https://nextcloud.markus-raab.org/nextcloud (you missed the /nextcloud). You can also easily test via curl:

`curl -sS -d "{\"token\": \"$CHAT\", \"message\": \"$*\"}" -H "Content-Type: application/json" -H "Accept: application/json" -H "OCS-APIRequest: true" -u "user:password" https://nextcloud.markus-raab.org/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/$CHAT`
