### ISSUE TITLE
running opensesame causes panic with no information about the panic

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#6]
Running opensesame default, without configuring, the program abort with no further information. So there is no information about the problem.

`thread panicked while processing panic. aborting.
Abgebrochen (Speicherabzug geschrieben)`

**Comment by markus2330** [comment]
Thanks for reporting the issue! Is this the problem you could solve by commenting out line 164 in src/main.rs (panic::set_hook)? Maybe we should add a configuration option for that.

**Comment by fel115** [comment]
Yes. I am going to implement the CLIOptions module (https://crates.io/crates/clioptions). In case we need more CLIOption in the future.

**Comment by markus2330** [comment]
Architectural changes should always be discussed in advance. We already use Elektra, which has support for command-line options: https://www.libelektra.org/tutorials/command-line-options but we shouldn't put time into this now.

Urgent now is that these beginners steps get documented, as they will be forgotten later.
