### ISSUE TITLE
Mirror libelektra-dev:armhf to infrastructure

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#61]
The Jenkins pipeline sometimes [fails](https://build.libelektra.org/blue/organizations/jenkins/opensesame/detail/PR-59/3/pipeline) by creating the docker-image.

**Comment by 4ydan** [comment]
@atmaxinger does this maybe have something to do with your website?

**Comment by atmaxinger** [comment]
```[2023-08-16T08:31:01.666Z] #9 0.517   Could not connect to thesis.maxirlinger.at:443 (136.243.167.152). - connect (111: Connection refused)
```

Seems so. AFAIK, there was some maintenance work done overnight. But I got an email at 2 AM that the work had been finished.

**Comment by markus2330** [comment]
@4ydan Can we close this now? Or do you want to mirror the repo to our infrastructure with this issue already? (Should be done in the long run.)

**Comment by 4ydan** [comment]
> Or do you want to mirror the repo to our infrastructure with this issue already? (Should be done in the long run.)

Yes, lets rename this issue to "Mirror libelektra-dev:armhf to infrastructure" or something, if that is ok to @atmaxinger .
