### ISSUE TITLE
deb from build server does not work

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#68]
As discussed in #49 the package from the build server does not seem to work. We need to investigate what exactly is broken:

- [ ] does also a non-crosscompiled build deb fail?
- [ ] does the debug binary (which works) also work in systemd context?
- [x] does also a release build work?

## already tried, did not help

- [x] remove NoNewPrivileges=true and ProtectSystem=full from debian/service -> does not help

**Comment by fel115** [comment]
I tested the release version which is generated with `cargo build --release` and it worked, but the release version with `cargo deb` which I created with the `Dockerfile_cross` didn't work to execute. Now I am generating the `deb`-file on the olimex board and check if its working this way.

**Comment by fel115** [comment]
When I compile the `deb` file locally on the Olimex board everything is working fine. There has to be something wrong with the cross-compile image. Also in Issue #69.

**Comment by markus2330** [comment]
Thx for the investigation. Let us discuss this today.

**Comment by fel115** [comment]
The C macros `HAVE_DECL_TIOCM_RTS` and `HAVE_DECL_TIOCSRS485` need to be set. These two macros are used [here](https://github.com/stephane/libmodbus/blob/master/src/modbus-rtu.c#L982). And in [this file](https://github.com/stephane/libmodbus/blob/master/configure.ac) `line 136 and 138` there is a check for this macros. 

@4ydan maybe you have an idea how to set this macros in cross-env.

**Comment by 4ydan** [comment]
Thank you for the details, I will let you when I have found something.

**Comment by markus2330** [comment]
@fel115 very good catch, this very much looks like you found the problem.

**Comment by 4ydan** [comment]
```
apt install linux-libc-dev:armhf
```
solved the issue for me

**Comment by fel115** [comment]
It isn't working, getting still the same error on the 'Messstation'
```bash
Aug 22 21:25:37 messstation opensesame[23540]: Couldn't ping Failed to init libmodbus connection: Rtu Error: "rtu_set_serial_mode" because https://nextcloud.markus-raab.org/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/vmdtygvk: Server Error: 500 Internal Server Error
```
