### ISSUE TITLE
Remove AutoClose garage feature

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#7]
Currently the garage door has an "automatically close later" feature by double pressing the button. This is, however, buggy, as it will also "automatically open later", which is quite surprisingly.

I think best is to completely remove that feature.

**Comment by markus2330** [comment]
@fel115 this should be a quite easy feature to start with

**Comment by fel115** [comment]
@markus2330  which button is pressed for this feature?

**Comment by markus2330** [comment]
Everything related to GarageChange::AutoClose (double click on *_UNTEN*)

**Comment by fel115** [comment]
Whats the difference between `taster_tor_oben` and `taster_tor_unten`, are these two taster, one for closing and the other for opening the door? And which would be for which case?

**Comment by markus2330** [comment]
> Whats the difference between taster_tor_oben and taster_tor_unten, are these two taster, one for closing and the other for opening the door? And which would be for which case?

No, one of them is for lights, the other for the garage door. So there is only one button relevant for the garage door.

> So the other AutoClose feature is still needed, to close the door immediately?

No, the AutoClose feature can be removed completely. (AutoClose === double press garage feature) I renamed the issue to hopefully bring in more clarity.

> But if you click the button twice, the door is going to be closed 2 min after the button clicks.

This is exactly the behavior that should be removed. In the code it is called "AutoClose".

Please add test cases for the other features (normal opening and closing of garage door).
