### ISSUE TITLE
Validator config poorly documented

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#76]
@markus2330 should the validator be configured?  I tried to add `validator = [3,0,4]` but it didn't work as expected.

**Comment by markus2330** [comment]
Do you mean "How can I configure the validator?"?

There is an example in ansible/playbook.yaml:

```yaml
              validator:
                'test': "[14, 15, 13, 15, 11, 15, 7, 15]"            

```

So it is a map of names to codes (and not directly a code as you tried).

But the example is still  broken, the `[]` are wrong. Pls fix. Correct is e.g.:

```yaml
        validator:
           'uns mit 12-34': "14, 12, 13, 15, 11, 3, 7, 15"
```


or in TOML syntax:

```
validator."uns mit 12-34" = "14, 12, 13, 15, 11, 3, 7, 15"
```

**Comment by fel115** [comment]
Yes, this is what I searched for. I thought I had seen it, but couldn't remember where. Thanks.

**Comment by markus2330** [comment]
I reopened as task to document the validator spec properly
