### ISSUE TITLE
Docu: Async Architecture and Interfaces

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#77]
# Async Architecture
The following modules can be disabled through elektra config.
- bat.rs
- buttons.rs + garage.rs
- clima_sensor_us.rs
- environment.rs
- garage.rs
- mod_ir_temp.rs
- pwr.rs
- sensors.rs
- ssh.rs
- validator.rs
- watchdog.rs

`config.rs` and `nextcloud.rs` are the minimal modules, which are needed for running Opensesame. Or should it be possible to replace `nextcloud` with an std-output?

# Module Interfaces
### 1.1. new(config) -> Self; 
This function returns a new object of the struct. According to the config in elektra it returns an default object or a object with all data like 'libmodbus' connection, 'i2c' connection. 
### 1.2. All pub functions need to check if this object is enabled or disabled, with a variable in the struct.
If a module is disabled it returns an error code that indicates that the module is disabled.
### 2.1. new(config) -> Self; and new_default() -> Self;
These two functions are needed because if a module is disabled the main loop calls `new_default() -> Self` to get a default object, so the variable in `main` is not uninitialized. The variable is overwritten with ` new(config) -> Self` if the module is enabled. So it would be possible to enable and disable modules during runtime.
### 2.2 Main function
In the `main`, it would be only if conditions for every module.

**Comment by horenso** [comment]
2.1. Why don't we keep a collection of modules (Like a `Vec<dyn Module>` or something like that)? That seems better than having dummy objects.

I imagine it something like this:


```rust
use tokio::io::{self, AsyncBufReadExt};

pub async fn read_device_file(device: &str) {
    let file = tokio::fs::File::open(device).await.unwrap();
    let reader = io::BufReader::new(file);

    let mut lines = reader.lines();
    while let Some(line) = lines.next_line().await.unwrap() {
        println!("Read from device: {}", line);
    }
}
``` 

and then in main:

```rust
#[tokio::main]
async fn main() {
    ...

    if condition_1 {
        tokio::spawn(module1::read_device_file("/dev/test1"));
    }

    if condition_2 {
        tokio::spawn(module1::read_device_file("/dev/test2"));
    }

    loop {
        // here we listen to config/nextcloud changes
    }
}
```

Note that we don't have to have a dynamic approach, meaning that you cannot enable a disabled module without restarting.

**Comment by horenso** [comment]
I think the two challenges are:
1. How can we have clean error handling?
2. How can we share a module like Nextcloud? I suppose we need to work with `Mutex`s so that Nextcloud should ask a `state` variable that is owned by the module.

**Comment by fel115** [comment]
> 1\. How can we have clean error handling?

I thought about something like that: 
```rust
pub enum Error<E> {
    I2C(E),
    MODBUS(E),
    DISABLED,
    ... 
}
```
> 2\. How can we share a module like Nextcloud? I suppose we need to work with `Mutex`s so that Nextcloud should ask a `state` variable that is owned by the module.

Do we need to share the Nextcloud module? We could create a Nextcloud object for every module or is that problematic?

3. What we also need to think of is, that many modules use timeouts that depend on the main-loop, because the main-loop sleeps for 10ms every duration. So if a timeout is set to `1000` it means 10 seconds. If we don't have any sleep we need to manage this differently.

**Comment by markus2330** [comment]
Next steps:

- create a PR where the interface is described in (pseudo) Rust code.
- ask further questions here as needed

> config.rs and nextcloud.rs are the minimal modules, which are needed for running Opensesame. Or should it be possible to replace nextcloud with an std-output?

If nextcloud fails to send, there is a message to stderr anyway. Having exchangeable modules for different chats is out-of-scope.

>new(config) -> Self;

We need a description in which situations it is allowed to fail. I think it should always succeed, even if it is totally broken. Then the object simply disables itself.

> If a module is disabled it returns an error code that indicates that the module is disabled.

How does it return the error code?

> These two functions are needed because if a module is disabled the main loop calls new_default() -> Self to get a default object, so the variable in main is not uninitialized.

I think it is more pretty if all of this happens within `new(config) -> Self`? So if it is disabled, a default Self doing nothing is returned.

> In the main, it would be only if conditions for every module.

I don't understand the sentence.

> With Tokio we can also just spawn threads for each module.

We should avoid that. Spawning a thread for a module is only last resort if everything else fails. Functional better is an architecture where tasks are delegated to a thread pool  (needing less resources as it spawns less threads, ideally only a thread per CPU).

> Note that we don't have to have a dynamic approach, meaning that you cannot enable a disabled module without restarting.

What can happen is that at runtime a module fails and it needs to be disabled as the error is permanent. (To not get errors for each time calling `handle()`.)

> How can we have clean error handling?

Yes, this is an important topic.

> How can we share a module like Nextcloud? I suppose we need to work with Mutexs so that Nextcloud should ask a state variable that is owned by the module.

The imho prettiest solution is that modules provide means to tell that something should be communicated and main or a dispatcher forwards this information to Nextcloud. Then the modules would not know anything about Nextcloud. This is also currently the case.

Easier/more flexible for modules is probably what you suggest. I am okay with both.

The big question is how you want to solve the incoming chat messages.

> Do we need to share the Nextcloud module? We could create a Nextcloud object for every module or is that problematic?

Yes, it is problematic, as then you would have N connections to Nextcloud. Ideally you would only have one (or one per thread if you don't want mutex at all).

>  What we also need to think of is, that many modules use timeouts that depend on the main-loop, because the main-loop sleeps for 10ms every duration. So if a timeout is set to 1000 it means 10 seconds.

This 10ms raster was only a hack for not having proper scheduling of tasks. It is better if either

- we hardcode how often which module gets called. So if the module only needs to be called every second, it also only gets called every second (and not 100 times, ignoring 99 times).
- modules tell when they should be called again (a bit more flexible but might be also more complicated. The current code does not necessarily need it. In some cases it would have been nice to have, e.g. for buttons you typically want every 10ms but for relay switching 10ms is too fast).

**Comment by fel115** [comment]
Issue # #74

**Comment by markus2330** [comment]
> But how does the calling function then know, what has happened? So the user would think the module is loaded but it isn't.

I thought that there is some `status()` function that tells the framework if a module is disabled.

> I meant that only the main loop checks if an object of the modules should be created.

I think it is simpler if modules decide this internally. There might be more tricky situations of disabling which imho belong to the module and not to main.

> So do you mean, that we have a thread per module, but the module-threads are added to a pool, where they are executed one by one?

No, there is only the main thread and a thread pool, empty when starting. The main thread is doing the tokio mainloop and the thread pool executes longer tasks to never block the mainloop (if needed). The modules don't have threads on their own but their tasks get assigned to any of the threads in the pool.

Probably an existing thread pool implementation should be used, in a quick search I found:

- https://docs.rs/rayon/1.3.0/rayon/struct.ThreadPool.html
- https://docs.rs/tokio-threadpool/latest/tokio_threadpool/

@fel115 please have a better look at options available, write a decision about that. You might be able to use this research in your thesis. E.g. see https://www.usenix.org/conference/atc20/presentation/boucher (only meant as hint for your thesis, I don't propose that we use this in Opensesame).

>  Is it possible for the modules to add their messages to a queue? So the modules can't overwrite the content of other modules? Or doesn't it work because of the borrowing of the nextcloud object?

Is this question to me or @horenso? What did you find out so far?

> So I think it would be easy to ask the server for new messages every few times. And for that async isn't necessary. You only need to save the ID of the last read message and then you are able to collect all new messages.

The http requests with lookIntoFuture might take up to 60 seconds until you get an answer. So working async there makes sense that there doesn't need to be a dedicated thread waiting so long.

**Comment by horenso** [comment]
> We should avoid that. Spawning a thread for a module is only last resort if everything else fails. Functional better is an architecture where tasks are delegated to a thread pool (needing less resources as it spawns less threads, ideally only a thread per CPU).

When you use
```
#[tokio::main]
async fn main() -> io::Result<()> {
```

tokio starts a runtime with as many worker threads as there are cores on a CPU. `tokio::spawn` spawns lightweight, green threads, that are managed by the runtime and are mapped to actual OS threads.

**Comment by markus2330** [comment]
> tokio starts a runtime with as many worker threads as there are cores on a CPU

This is exactly what we want.

> tokio::spawn spawns lightweight, green threads, that are managed by the runtime and are mapped to actual OS threads.

If used correctly, this is then harmless and such a green thread could be used for each module, if needed.

> I have a question about the signals @markus2330 are any of the signals neccessary, or where they just a hack because of no event loop? Is the program required to respond to any signals? (I mean apart from SIGINT, like the user signals or SIGALRM).

- SIGUSR2 and SIGALRM are actually used in application logic (triggered via ssh).
- SIGHUP is used by Elektra via files/reload-opensesame. files/reload-opensesame could be changed to completely restart opensesame instead.
- SIGUSR1 is a useless feature, can be deleted

Please add documentation for that.

> For communication between modules we'd like to use mpsc::channel.

:+1: sounds good to me.

> We drew a diagram that starts to outline the current architecture.

Thx for drawing it, looks great. Please keep updated.

**Comment by horenso** [comment]
Here is our next iteration (still WIP)

![Updated version](https://github.com/ElektraInitiative/opensesame/assets/41299302/991775e0-ac0a-4e0d-8fe2-d3c71c1e40ef)

**Comment by fel115** [comment]
![information_flow_color drawio](https://github.com/ElektraInitiative/opensesame/assets/133339595/bf5c1060-ed57-4327-9544-1551769aee8e)

I created a new draw.io and described the information flow between the Modules. The only connection I didn't draw, is the read connection to the config-Module because every Module does this and I haven't had enough space :sweat_smile:

**Comment by fel115** [comment]
According to the issue with the weather station, I found an async implementation of [Modbus](https://github.com/slowtec/tokio-modbus) and the problem with setting the pins for reading and writing could be managed by the Linux system https://github.com/slowtec/tokio-modbus/issues/182

**Comment by horenso** [comment]
> I found an async implementation of [Modbus](https://github.com/slowtec/tokio-modbus)

That looks very promising!

**Comment by markus2330** [comment]
Seems all is done now! :heart: 

Info here should be moved to docu now.
