### ISSUE TITLE
GPIO Pins Garage

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#78]
># GPIO Input
>## Layout Platine
>  Taster Eingang Oben -> Pin40 GPIO234 EINT10
    Taster Eingang Unten -> Pin38 GPIO235 EINT11
    Taster Tor Oben -> Pin36 GPIO236 EINT12
    Taster Tor Unten -> Pin32 GPIO237 EINT13
    Schalter Garagentor Endposition -> Pin26 GPIO238 EINT14

Is this right? On which connector should this connection be? As I searched the [datasheet](https://www.olimex.com/Products/SOM/A20/_resources/A20-Brief-2013-02-27.pdf) I found `EINT10` on `PH10` which is `GPIO234` on the olimex board. But I found it in the [Lime2-datasheet](https://www.olimex.com/Products/OLinuXino/A20/A20-OLinuXino-LIME2/resources/A20-OLinuXino-LIME2-UM.pdf) at `GPIO-3` on `Pin13` and not `Pin10`. I am a bit confused.

**Comment by markus2330** [comment]
It is with the large GPIO5 connector of LIME2-SHIELD. Please look there how it is connected and update documentation.

**Comment by fel115** [comment]
Oh thanks, know it makes sense. On the olimex board  it is `GPIO-3 Pin10`.
