### ISSUE TITLE
simulate i2c device

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#8]
So I only need the Token ? Do I need to configure my nextcloud account? 
Now I am getting this Error:

`Couldn't ping 👋 Opensesame 0.7.6 init 2023-05-25T19:44:20.353056793+02:00 because https://nextcloud.markus-raab.org/ocs/v2.php/apps/spreed/api/v1/chat/<THIS IS THE TOKEN>: Client Error: 404 Not Found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Keine Berechtigung" })', src/buttons.rs:132:65
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: opensesame::buttons::Buttons::new
   4: opensesame::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

_Originally posted by @fel115 in https://github.com/ElektraInitiative/opensesame/issues/5#issuecomment-1563300690_
            
As I backtraced this panic I recognised , that it isn't caused by Nextcloud instead it is caused by the button.rs LinuxI2CDevice. I think its because my devl-env has no `/dev/i2c-2` device. This could be solved by simulating the i2c device. Online I found the i2c-stub (https://www.kernel.org/doc/html/latest/i2c/i2c-stub.html), which cloud be the perfect tool.

**Comment by markus2330** [comment]
Alternatively, and probably better for tests, is that you use the mocking from the i2c lib https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html

But I wouldn't do that now, it is quite challenging from Rust point of view.
