### ISSUE TITLE
Garage door endposition

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#80]
Is the garage door open if the endposition switch is reached or closed?  Because the status says `Closed` and the message says `Garage door closed.`.

https://github.com/ElektraInitiative/opensesame/blob/5ede5a8dc4a27e5cd733353df23f727fd7485a8e/src/main.rs#L518-L529

**Comment by markus2330** [comment]
The garage door is closed if the endpoint switch is closed.

You found a bug, great job! :heart: :rocket: 

Both the set_info_door text (but not the symbol) is wrong.

**Comment by markus2330** [comment]
Maybe you already fixed it but I cannot check due to #106

**Comment by fel115** [comment]
should be fixed with PR #112
