### ISSUE TITLE
document pull-up for Garage

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#81]
What does it change, if I set the GPIO3 of the MOD-IO2 board to 5V? And setting 5V on the GPIO-Pin might be to much?

https://github.com/ElektraInitiative/opensesame/blob/5ede5a8dc4a27e5cd733353df23f727fd7485a8e/doc/Garage.md?plain=1#L6

Also is it possible to use the `garage module` with the `buttons module`?
 If I enable garage it is doing some weird stuff.
E.g. switching of relays and the buttons can't be pressed. Is there a relation to the 5V on GPIO3? 
If a `Taster` of the garage module is pressed, does it set the connected GPIO-Pin to GND?

**Comment by fel115** [comment]
Ok now I connected Leds to the GPIO-Pins, and only the `Taster Eingang Oben` and `Taster Eingang Unten` seem to have a pull-up. But I have no idea how these are configured as pull-up inputs :thinking:

**Comment by fel115** [comment]
Now I tested it with external pull-ups and it is working. So maybe the Lim2-Shield pulls the input pin up ?

**Comment by markus2330** [comment]
>  Is it possible to use the 3.3V?

For input pins with the right 3.3V (from the board itself) it should be possible but pull-ing up with a switch to ground ground is simpler/safer.

> Which size should be the pull-up resistor 47k?

Yeah, iirc I always used 47kΩ. Smaller values should also work but they need more energy. For larger values you need to test for yourself if it provides stable results.

>  Is the GPIO-Pin automatically a pull-up input, if it's configured as input?

There are big tables in the Internet/Olimex forum that tell the default configuration for each pin.

> Now I tested it with external pull-ups and it is working.

Great!

> So maybe the Lim2-Shield pulls the input pin up ?

I don't think so. More likely I forgot to document that a 47kΩ pull-up is needed.

**Comment by markus2330** [comment]
Is docu updated about that pull-up?

**Comment by fel115** [comment]
Done in PR #115
