### ISSUE TITLE
async weather station

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#82]
> According to the issue with the weather station, I found an async implementation of [Modbus](https://github.com/slowtec/tokio-modbus) and the problem with setting the pins for reading and writing could be managed by the Linux system https://github.com/slowtec/tokio-modbus/issues/182

_Originally posted by @fel115 in https://github.com/ElektraInitiative/opensesame/issues/77#issuecomment-1704944903_

**Comment by markus2330** [comment]
(I took this discussion away from #77 as we decided to do this after buttons)

@fel115 this sounds promising.

I assume using this module is nearly a rewrite of modbus related code?

Do you know what they mean with "the RS-485 feature of the serial"?
Is this via implementing a Linux driver?

**Comment by fel115** [comment]
Yes, but I think it wouldn't be that much, because we only read the registers and that is one function.

Yes, I think we can set the pins for the ioctl calls in the system, so we don't need a custom function like in libmodbus-rs. But I haven't done further research.

**Comment by fel115** [comment]
[This](https://github.com/slowtec/tokio-modbus/issues/127) cloud also be an idea. The problem is that the pins on the lime2-shield don't forward the Uart connections' RTS-Pins.

**Comment by markus2330** [comment]
Seems to be done! :heart:
