### ISSUE TITLE
weather station: Böe functionality not working

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#84]
@fel115 can you recheck if the correct register is used for the Böe functionality. Afaics it was always 0.0 and there definitely was some gust of wind from time to time.

**Comment by fel115** [comment]
Yes, it uses the right register (0x88B9), which can be found on [here](https://www.vetterag.ch/images/pdf/thies/BA/4.920x.x0.xxx_ClimaSensor_US_d.pdf) on page 35. Maybe there is a problem with `conv_vec_to_value_u(...)` function. The data on opensensemap, also show that they are different from `0.0`.

**Comment by markus2330** [comment]
Thx for quickly looking into it. When did you see a value != 0.0, I didn't notice it.

Do we have "Mittelungszeitraum auf mindestens 3 Sekunden"‚ i.e. AV‘ >= 30?

**Comment by fel115** [comment]
It seems to be set to 1s, so that's the reason. We need to set it to 30.

**Comment by fel115** [comment]
Is working now.
![image](https://github.com/ElektraInitiative/opensesame/assets/133339595/ec2789c4-11f0-4359-bb98-07954b511d80)

**Comment by markus2330** [comment]
seems to be broken again, probably Opensesame needs to set the register by itself?

![image](https://github.com/ElektraInitiative/opensesame/assets/7949075/6ef80219-854a-4162-b4fb-9e2ddb189bef)

**Comment by fel115** [comment]
> seems to be broken again, probably Opensesame needs to set the register by itself?
> 
> ![image](https://user-images.githubusercontent.com/7949075/273187569-6ef80219-854a-4162-b4fb-9e2ddb189bef.png)

Normally it should be all stored on the weather station. But I am going to check it. :thinking:

**Comment by fel115** [comment]
I think I found the issue 
https://github.com/ElektraInitiative/opensesame/blob/c519a6b5284660fffc8122e3e1438fca25954ae0/src/weather_station/write_to_reg.rs#L38

In this case, we only write to one register. So we don't overwrite the user; the changes only get permanent if we change from ADMIN user back to READ ONLY user.

**Comment by markus2330** [comment]
Great, thx.
