### ISSUE TITLE
weather station: uploads sometimes broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#85]
Nearly every day there are warnings like:

```
https://api.opensensemap.org/boxes/64cb602193c69500072a580f/data: timed out
https://api.opensensemap.org/boxes/64cb602193c69500072a580f/data: Server Error: 502 Bad Gateway
```

Most of the time it is 502 Bad Gateway.

I hope this can improve with the async framework, can we maybe try again a few times? (retrying must end within a minute though, as then there is already new data and we don't want to spam the server if it has capacity issues.)

**Comment by horenso** [comment]
How frequent is the communication to/from the weather station?

**Comment by fel115** [comment]
The weatherstation updates every minute.
