### ISSUE TITLE
API: chat(kind, msg) and status(kind, msg)

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#87]
would be the more pretty API.

kind an enum

- with default, ping, licht for chat and
- online, env and door for status

**Comment by fel115** [comment]
Implementation done in #75.

**Comment by markus2330** [comment]
Great! We should merge #75 soon, as it seems it is already more than a simple refactor to async.

**Comment by markus2330** [comment]
@fel115 is this fixed?

**Comment by fel115** [comment]
Yes
