### ISSUE TITLE
Problems with autostart after boot

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#89]
The following error occurs if opensesame starts automatically after boot up: 
```bash
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("nextcloud.markus-raab.org")), port: None, path: "/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/ftusupec", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Tempor?rer Fehler bei der Namensaufl?sung" })) }', /home/smod/Bachelorarbeit/GitHub/jannis_repo/opensesame/src/nextcloud.rs:268:14
```
I think there is some issue with the lookup of the domain, during start. If I start opensesame manually with `sudo systemctl start opensesame` no error occurs during startup of opensesame.

**Comment by markus2330** [comment]
Do you use the service file? (Proper Debian install.) I once fixed a bug that looks very much related: 554a9c02fa3b917c7ffd4993962ae20541199ed7

**Comment by fel115** [comment]
The service file looks like this in commit [554a9c0](https://github.com/ElektraInitiative/opensesame/commit/554a9c02fa3b917c7ffd4993962ae20541199ed7):

```bash
[Unit]
Description=opensesame
Wants=network-online.target
After=network.target network-online.target

[Service]
Type=simple

User=olimex
Group=olimex
NoNewPrivileges=true
ProtectSystem=full

Nice=-20
CPUSchedulingPriority=80
IOSchedulingClass=realtime
IOSchedulingPriority=0

Restart=always
ExecStart=/usr/bin/opensesame

[Install]
WantedBy=multi-user.target
```

**Comment by markus2330** [comment]
Is this problem already fixed? Maybe you need to add one more "After" target, something related to resolver/DNS?

**Comment by fel115** [comment]
No its not fixed. I will try to add the resolver/DNS. Thanks

**Comment by fel115** [comment]
I now tried to add `nss-lookup.target` and `nss-user-lookup.target`, but it still doesn't work. I also added `PreExecStart=/bin/sh -c 'until ping -c1 nextcloud.markus-raab.org; do sleep 1; done'` but I got the same error. So there is another problem then, and the network and nslookup work. Maybe async-opensesame depend on another component, but I don't have any idea.

Now I am also getting 'Network unreachable', but `ping` in the `PreExecStart` worked

**Comment by markus2330** [comment]
`nss-lookup.target` sounds quite promising. Please add it to the PR, maybe there is simply a typo?

Should't it be ExecStartPre? But I don't like this solution anyway. Let us better send a "hello" Nextcloud message at the beginning of Opensesame, with several retries and a second delay in between.
