### ISSUE TITLE
Seperate Validator- and Buttons-Modul

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#92]
Now the Validation of an input is done in the `get_background_task` of the Buttons module. And the idea is, that validation only needs to be checked if a Pin-Button was pressed. There could be a channel between Buttons and the Validator, and the Buttons module sends every new sequence to the Validator module. The validator module also needs to send commands to the Buttons module to `show_wrong_input`, `ring_bell`, `open_door` and `switch_lights`. 

The handling of `Timeout` and `SequenceTooLong` might be tricky or need a new structure for the validation. Special Commands for that can be created on Buttons side.

**Comment by markus2330** [comment]
I don't think this is needed.
