### ISSUE TITLE
Documentation of new modules 

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#99]
Create documentation in the doc folder for the new modules:
- [x] audio.rs
- [x] bat.rs (Capacity)
- [x] nextcloud.rs (Commands)
- [x] ping.rs 
- [x] signals.rs
- [x] types.rs

and then remove:

- [x] [doc/modules.md](https://github.com/ElektraInitiative/opensesame/pull/75/files#diff-e75ecc4ae130b5c650f8517d7b1bc06dcfd281b5231b161d27f398e220dd6638)

**Comment by markus2330** [comment]
I added

"and then remove [doc/modules.md](https://github.com/ElektraInitiative/opensesame/pull/75/files#diff-e75ecc4ae130b5c650f8517d7b1bc06dcfd281b5231b161d27f398e220dd6638)"

above.

**Comment by markus2330** [comment]
@fel115 can you please merge the content of https://github.com/ElektraInitiative/PermaplanT/pull/956 and [doc/modules.md](https://github.com/ElektraInitiative/opensesame/pull/75/files#diff-e75ecc4ae130b5c650f8517d7b1bc06dcfd281b5231b161d27f398e220dd6638) into the proper places in `doc/<module>`?

**Comment by fel115** [comment]
What does the [PermaplanT PR](https://github.com/ElektraInitiative/PermaplanT/pull/956) do? Adding a guide?

**Comment by markus2330** [comment]
Sorry, wrong link (copy&paste error), I mean #77 etc.

**Comment by fel115** [comment]
See PR #115

**Comment by markus2330** [comment]
Great, except of what is written in #101 it is a good start for the module documentation.
